name: node pipeline

on:
 push:
  branches: ["main"]

jobs:
 node:
  runs-on: wsl-linux
  steps:
   - name: Checkout repository
     uses: actions/checkout@v7
   - name: Set up Node.js
     uses: actions/setup-node@v7
     with:
      node-version: '24'
   - name: Install packages
     run: |
      npm install
      npm install dotenv
      npm install express
   - name: Run application
     run: |
      npm server.js &
      sleep 5
      curl http://localhost:8080
      curl http://localhost:8080/health
      pkill -f node
